### ISSUE TITLE
右クリックが視点に影響を与える

### ISSUE THREAD

**Issue by yuto-moriizumi** [xr-hamaria/virtual-inf#10]
マウスで右クリックをすると、視点が反転するようです
一番でっかい建物付近で、歩きながら右クリックを押すとこの現象を再現しやすいです
右クリックしたときに必ず視点がおかしくなるわけではないようです。

**Comment by yuratwc** [comment]
直した。多分。 https://github.com/xr-hamaria/virtual-inf/commit/0c30235c0c4750049b322bf910890d01d7a3e758
