### ISSUE TITLE
操作説明と動作が対応していない

### ISSUE THREAD

**Issue by yuto-moriizumi** [xr-hamaria/virtual-inf#11]
操作説明には
↑キーで高度を上げ、↓キーで高度を下げると説明されています。
しかし、VRモードでは前進と後退に割り当てられているようです。
俯瞰モードでは矢印キーは動作しません（仕様かもしれません）

**Comment by toyakun** [comment]
修正してみました。これで合ってますかね？ https://github.com/xr-hamaria/virtual-inf/commit/7a56328e71f6c33f00bad0eabf75db6551c49feb
