### ISSUE TITLE
幹が水色の木がある

### ISSUE THREAD

**Issue by yuto-moriizumi** [xr-hamaria/virtual-inf#9]
こちらは仕様でしょうか？

![2020-8-3_1-55_00](https://user-images.githubusercontent.com/42604418/89127916-95662c80-d52c-11ea-90c8-43aaa5f6fd05.jpg)

**Comment by toyakun** [comment]
誤操作してしまったものです。次回更新時に修正します。

**Comment by toyakun** [comment]
fixed in https://github.com/xr-hamaria/virtual-inf/commit/ea786f87cba0ee355f66a77f60eade36d03c11b0
